"""
common.py  (shared helpers, used by every phase)
------------------------------------------------
This is the one place that knows about paths, reads the raw .s16p files, turns them
into the 2-channel [real, imag] images the networks eat, and holds the small pieces
that more than one phase needs (the mirror-symmetry feature and the little CNN
classifier). I kept all of this in a single file on purpose, so when I forget how
something works I only have one place to look.

The data representation, in one picture:

  raw S : complex array [F=1001, 16, 16]           (frequency, antenna, antenna)
    -> flatten the 16x16 antenna grid   -> [F, 256]
    -> transpose                         -> [256, F]      (256 antenna-pair rows)
    -> resample frequency F -> 256        -> [256, 256]
    -> stack (real, imag) as 2 channels   -> [2, 256, 256]  float32

I keep BOTH the real and the imaginary part (the paper uses magnitude only). That
keeps the phase, keeps the Blood - Healthy subtraction exact, and it is the only way
the Phase 6 physics checks are even possible.
"""
import os, re, glob, csv
import numpy as np
import torch, torch.nn as nn


# ============================================================================
# 1. PATHS  (everything is relative to the project folder, so the repo is portable)
# ============================================================================
PROJ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_ROOT = os.path.join(PROJ, "data", "CST-New-300-16Q-1216-Final_split")

OUT = os.path.join(PROJ, "outputs")
CACHE_DIR = os.path.join(OUT, "cache")
CACHE = os.path.join(CACHE_DIR, "raw")          # the cached .npy images (regenerated by phase 1)
INDEX = os.path.join(CACHE_DIR, "index.csv")     # one row per file + its labels

# One numbered folder per phase, so the results are easy to find and to trust.
DIR_1 = os.path.join(OUT, "1_preprocess")
DIR_2 = os.path.join(OUT, "2_classification_before")
DIR_3 = os.path.join(OUT, "3_domains")
DIR_4 = os.path.join(OUT, "4_cyclegan")
DIR_5 = os.path.join(OUT, "5_classification_after")
DIR_6 = os.path.join(OUT, "6_physics")
DIR_7 = os.path.join(OUT, "7_final_comparison")

for _d in (CACHE, DIR_1, DIR_2, DIR_3, DIR_4, DIR_5, DIR_6, DIR_7):
    os.makedirs(_d, exist_ok=True)

# The deliverable: the trained clutter-removing generator G lives here.
FINAL_MODEL = os.path.join(DIR_4, "FINAL_generator_G.pt")

DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"

N_ANT = 16                 # antennas / ports
N_PAIR = N_ANT * N_ANT     # 256 antenna-pair channels
F_OUT = 256                # frequency bins after resampling (square 256x256 image)

# I split by head so the two test heads are never seen while training.
TRAIN_HEADS = list(range(1, 25))     # heads 1..24
VAL_HEADS = list(range(25, 29))      # heads 25..28
# the test heads (29, 31) come from the dataset's own test/ folder


# ============================================================================
# 2. READING THE RAW FILES  (filename -> labels, .s16p -> image)
# ============================================================================
def parse_name(path):
    """Pull the labels out of a filename. Works for BLOOD_* and HEALTHY_* files.
    The filename is our free label: it tells us bleed vs healthy, which head it is,
    and (for bleeds) where the blood sits and how big it is."""
    b = os.path.basename(path)
    info = {"path": path, "file": b}
    if b.upper().startswith("BLOOD"):
        info["label"] = "blood"            # 1 = has a bleed
        info["y"] = 1
        info["head"] = int(re.search(r"head(\d+)", b).group(1))
        m = re.search(r"_x(-?[\d.]+)_y(-?[\d.]+)_z(-?[\d.]+)_r([\d.]+)_v(\d+)", b)
        if m:
            info["bx"], info["by"], info["bz"] = float(m.group(1)), float(m.group(2)), float(m.group(3))
            info["radius"], info["volume"] = float(m.group(4)), int(m.group(5))
    else:
        info["label"] = "healthy"          # 0 = healthy
        info["y"] = 0
        info["head"] = int(re.search(r"HM(\d+)", b).group(1))
        rm = re.search(r"Run(\d+)", b)
        info["run"] = int(rm.group(1)) if rm else 0
    return info


def list_split(root, split):
    """Return (blood_files, healthy_files) for split in {train, test}."""
    blood = sorted(glob.glob(os.path.join(root, split, "Blood", "*.s16p")))
    healthy = sorted(glob.glob(os.path.join(root, split, "Healthy", "*.s16p")))
    return blood, healthy


def load_raw_S(path):
    """Load one .s16p file -> complex ndarray [F, 16, 16]. Uses scikit-rf."""
    import skrf
    return skrf.Network(path).s          # complex128 [F, 16, 16]


def S_to_image(S, f_out=F_OUT):
    """complex S [F,16,16] -> float32 image [2, 256, f_out] (channel0=real, channel1=imag).
    The frequency axis is linearly resampled to f_out points. Returns raw physical
    S units (no normalisation yet)."""
    from scipy.interpolate import interp1d
    F = S.shape[0]
    flat = S.reshape(F, N_PAIR).T            # [256, F]
    if F != f_out:
        x_old = np.linspace(0.0, 1.0, F)
        x_new = np.linspace(0.0, 1.0, f_out)
        flat = interp1d(x_old, flat, axis=1, kind="linear", assume_sorted=True)(x_new)
    return np.stack([flat.real, flat.imag], axis=0).astype(np.float32)   # [2,256,f_out]


def load_image(path, f_out=F_OUT):
    return S_to_image(load_raw_S(path), f_out=f_out)


# ============================================================================
# 3. THE CACHE INDEX  (so later phases load .npy fast instead of re-reading .s16p)
# ============================================================================
def read_index():
    with open(INDEX) as f:
        return list(csv.DictReader(f))


def load_split(rows, split, heads=None, label=None):
    """Return list of (array[2,256,256], y:int, head:int) for the matching rows."""
    out = []
    for r in rows:
        if r["split"] != split:
            continue
        if heads is not None and int(r["head"]) not in heads:
            continue
        if label is not None and r["label"] != label:
            continue
        arr = np.load(os.path.join(CACHE, r["cache"]))
        out.append((arr, int(r["y"]), int(r["head"])))
    return out


# ============================================================================
# 4. NORMALISATION for the classifier
# ============================================================================
def channel_stats(arrays):
    """mean/std per (real-imag channel, antenna-pair row), averaged over freq+samples.
    Shapes -> [2,256,1]. This removes the common-mode clutter level of each channel."""
    stack = np.stack(arrays, 0)                   # [N,2,256,256]
    mean = stack.mean(axis=(0, 3))                # [2,256]
    std = stack.std(axis=(0, 3)) + 1e-8           # [2,256]
    return mean[..., None].astype(np.float32), std[..., None].astype(np.float32)


def standardize(arr, mean, std):
    return (arr - mean) / std


# ============================================================================
# 5. THE LEFT-RIGHT SYMMETRY FEATURE  (this is what makes Phase 2 work)
# ============================================================================
def find_mirror_axis(healthy_arrays):
    """Find the mirror m that makes the HEALTHY scans most symmetric, using the
    permutation P(k) = (m - k) mod 16. A bleed is one-sided so it breaks this
    symmetry; the skull clutter is (mostly) symmetric so it cancels."""
    def to_grid(a):
        return (a[0] + 1j * a[1]).reshape(16, 16, -1)
    grids = [to_grid(a) for a in healthy_arrays]
    best_m, best_s = 0, 1e9
    for m in range(16):
        idx = [(m - k) % 16 for k in range(16)]
        s = np.mean([np.abs(g - g[np.ix_(idx, idx)]).mean() for g in grids])
        if s < best_s:
            best_s, best_m = s, m
    return best_m


def mirror_asym(arr, m):
    """arr [2,256,256] -> the asymmetry S - P S P, kept as [2,256,256] (real, imag)."""
    g = (arr[0] + 1j * arr[1]).reshape(16, 16, -1)
    idx = [(m - k) % 16 for k in range(16)]
    d = g - g[np.ix_(idx, idx)]
    d = d.reshape(256, -1)
    return np.stack([d.real, d.imag], axis=0).astype(np.float32)


def make_transform(kind, m):
    """Return f(arr[2,256,256]) -> repr[C,256,256] for kind in {raw, asym, raw+asym}."""
    if kind == "raw":
        return lambda a: a
    if kind == "asym":
        return lambda a: mirror_asym(a, m)
    if kind == "raw+asym":
        return lambda a: np.concatenate([a, mirror_asym(a, m)], axis=0)
    raise ValueError(kind)


# ============================================================================
# 6. THE SMALL CNN CLASSIFIER  (used for the before/after comparison)
# ============================================================================
class SParamCNN(nn.Module):
    def __init__(self, in_ch=2, p_drop=0.3):
        super().__init__()
        def block(i, o):
            return nn.Sequential(
                nn.Conv2d(i, o, 3, padding=1), nn.BatchNorm2d(o), nn.ReLU(inplace=True),
                nn.MaxPool2d(2))
        self.features = nn.Sequential(
            block(in_ch, 16), block(16, 32), block(32, 64),
            nn.Conv2d(64, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d(1))
        self.head = nn.Sequential(nn.Flatten(), nn.Dropout(p_drop), nn.Linear(64, 1))

    def forward(self, x):
        return self.head(self.features(x)).squeeze(1)


def _augment(x):
    """Mild, physically-sensible augmentation. I do NOT scramble the frequency axis,
    because the bleed's fingerprint sits at specific frequencies and a big roll would
    destroy the class signal. So just a tiny jitter and an optional +/-2 bin shift."""
    if np.random.rand() < 0.5:
        x = torch.roll(x, shifts=int(np.random.randint(-2, 3)), dims=-1)
    x = x + 0.02 * torch.randn_like(x)
    return x


def train_eval(train, val, test, mean, std, epochs=60, lr=1e-3, bs=16,
               seed=0, tag="phase2", verbose=True, in_ch=2):
    """train/val/test are lists of (arr, y, head). Returns metrics dict + model + history.
    `arr` may be any C-channel representation; set in_ch=C accordingly."""
    torch.manual_seed(seed); np.random.seed(seed)

    def to_tensors(ds):
        X = np.stack([standardize(a, mean, std) for a, _, _ in ds]).astype(np.float32)
        y = np.array([b for _, b, _ in ds], dtype=np.float32)
        return torch.tensor(X), torch.tensor(y)

    Xtr, ytr = to_tensors(train)
    Xva, yva = to_tensors(val)
    Xte, yte = to_tensors(test)

    model = SParamCNN(in_ch=in_ch).to(DEVICE)
    opt = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=epochs)
    lossf = nn.BCEWithLogitsLoss()

    def accuracy(X, y):
        model.eval()
        with torch.no_grad():
            p = torch.sigmoid(model(X.to(DEVICE))).cpu().numpy()
        return float(((p > 0.5).astype(int) == y.numpy().astype(int)).mean())

    n = len(Xtr); best_va = -1; best_state = None; hist = []
    for ep in range(epochs):
        model.train()
        perm = torch.randperm(n)
        for i in range(0, n, bs):
            idx = perm[i:i + bs]
            xb = _augment(Xtr[idx]).to(DEVICE)
            yb = ytr[idx].to(DEVICE)
            opt.zero_grad()
            loss = lossf(model(xb), yb)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
        sched.step()
        va = accuracy(Xva, yva); tr = accuracy(Xtr, ytr)
        hist.append({"epoch": ep, "train_acc": tr, "val_acc": va})
        if va >= best_va:
            best_va = va
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        if verbose and (ep % 5 == 0 or ep == epochs - 1):
            print(f"  ep{ep:02d}  train_acc={tr:.3f}  val_acc={va:.3f}  (best_val={best_va:.3f})")

    model.load_state_dict(best_state)
    metrics = {
        "tag": tag,
        "train_acc": accuracy(Xtr, ytr),
        "val_acc": accuracy(Xva, yva),
        "test_acc": accuracy(Xte, yte),
        "n_train": len(train), "n_val": len(val), "n_test": len(test),
    }
    return metrics, model, hist
